### ISSUE TITLE
[About] [Style] Membership Section - Membership description styling 

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#120]
### Description of Issue
This issue covers applying the below CSS properties to the **description** inside  <p> html element below section header - "Become a Member"
/* .site-about-description p */

font-family: Josefin Sans;
font-style: normal;
font-weight: 300;
font-size: 25px;
line-height: 25px;
letter-spacing: -0.02em;

color: #000000;
#### FROM:
There is no existing membership section in the already deployed website template

#### TO:
![image](https://user-images.githubusercontent.com/25425769/155892995-567fab39-26ae-4e52-844a-37b9f6d6f6e4.png)

**Comment by bluelotus03** [comment]
Completed
