### ISSUE TITLE
[About] [Style] Membership Section - Step One Header Styling

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#121]
### Description of Issue
This issue covers applying the below CSS properties to the section header inside HTML element h3 - "Step 1: Niner Engage"
/* H3 */

font-family: Montserrat;
font-style: normal;
font-weight: 500;
font-size: 30px;
line-height: 37px;
letter-spacing: -0.02em;

color: #0A0808;

#### FROM:
There is no existing membership section in the already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/25425769/155893166-c1e45c77-049c-422f-b7cf-d91a028d9d88.png)

**Comment by bluelotus03** [comment]
Completed
