### ISSUE TITLE
[About] [Style] Membership Section - Step One - What Happens header styling 

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#123]
### Description of Issue

This issue covers applying the below CSS properties to the header under step one inside HTML element h3 - "What happens from here?"
/* H3 */

font-family: Montserrat;
font-style: normal;
font-weight: 500;
font-size: 30px;
line-height: 37px;
letter-spacing: -0.02em;

color: #0A0808;

#### FROM:
There is no existing membership section in the already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/25425769/155893539-6a242ede-8ad6-4b67-9601-5784cc98c937.png)

**Comment by bluelotus03** [comment]
Completed
