### ISSUE TITLE
[About] [Style] Partnership Section - Section Header Styling

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#125]
### Description of Issue
This issue involves applying CSS properties to the section header inside HTML element h2 with content: "Partner with Us"
/* H2 */

font-family: Montserrat;
font-style: normal;
font-weight: normal;
font-size: 50px;
line-height: 61px;
letter-spacing: -0.02em;

color: #000000;

#### FROM:
There is no partnership section in an already deployed website template

#### TO:
![image](https://user-images.githubusercontent.com/25425769/155893932-ece746ab-11f9-4da5-915c-813cfe41822c.png)

**Comment by bluelotus03** [comment]
Completed
