### ISSUE TITLE
[About] [Style] Partnership Section - Styling Description under header 

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#126]
### Description of Issue

This issue involves applying CSS properties to the description with content: "This is a great way to advertise your business and network with up-and-coming women in tech."

/* .site-about-description p */

font-family: Josefin Sans;
font-style: normal;
font-weight: 300;
font-size: 25px;
line-height: 25px;
letter-spacing: -0.02em;

color: #000000;

#### FROM:
There is no partnership section in an already deployed website template
#### TO:

![image](https://user-images.githubusercontent.com/25425769/155894151-aa0b5ab1-f0af-46db-b0b4-0ce797a83a48.png)

**Comment by bluelotus03** [comment]
Completed
