### ISSUE TITLE
[About] [Style] Partnership Section - Sub headers styling  

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#127]
### Description of Issue
Apply below CSS properties to the subheaders enclosed in HTML element h3 
1. How to Partner on an Event We Host
2. How to Partner on an Event You Host
3. Event Options 
4. Previous partner events:

/* H3 */

font-family: Montserrat;
font-style: normal;
font-weight: 500;
font-size: 30px;
line-height: 37px;
letter-spacing: -0.02em;

color: #0A0808;

#### FROM:
There is no partnership section in an already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/25425769/155894378-67fad5f2-b0af-486d-bc83-b8c2571f7068.png)
![image](https://user-images.githubusercontent.com/25425769/155894388-f08485f2-fa97-4f0e-9878-6187c75da2f1.png)

![image](https://user-images.githubusercontent.com/25425769/155894418-e67c8ca1-f995-43a4-9d92-c9b647a15219.png)
![image](https://user-images.githubusercontent.com/25425769/155894425-9025cf00-0db3-4ab2-83de-e46b7f8232e5.png)

**Comment by bluelotus03** [comment]
Completed
