### ISSUE TITLE
[About] [Style] Partnership Section - Content Styling

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#128]
### Description of Issue
This issue involves applying of below CSS properties to the entire content under the partnership section except for all headers. Please refer to screenshots for more reference. 
/* .site-about-description p */

font-family: Josefin Sans;
font-style: normal;
font-weight: 300;
font-size: 25px;
line-height: 25px;
letter-spacing: -0.02em;

color: #0A0808;

#### FROM:
There is no partnership section in an already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/25425769/155894562-a010aa08-65eb-4869-817d-626dcf93a570.png)
![image](https://user-images.githubusercontent.com/25425769/155894568-3e408f76-cf8a-4b45-975e-e75b747d887c.png)
![image](https://user-images.githubusercontent.com/25425769/155894589-90b1ee87-c88c-49ab-af93-6c18ac5b2562.png)
![image](https://user-images.githubusercontent.com/25425769/155894595-8aded332-b3aa-4bd1-ab2a-23f1a68f296d.png)

**Comment by bluelotus03** [comment]
Completed
