### ISSUE TITLE
[About] [Content] Top Section - Logo and Intro

### ISSUE THREAD

**Issue by zshawar** [GWC-UNCC/Girls-Who-Code-at-UNCC#129]
### Languages Used
HTML

### Description of Issue
Need to add an image tag with our logo and an intro description underneath about us.

#### FROM:
This is an image of the current header, but we are not using this
![image](https://user-images.githubusercontent.com/77990816/155898314-e9a6def1-73a7-499e-a49c-6070932ae523.png)

#### TO:
![image](https://user-images.githubusercontent.com/77990816/155898378-045fd849-d82e-4df0-ad3b-f961854ee00e.png)

**Comment by bluelotus03** [comment]
Completed with PR #161
