### ISSUE TITLE
[About] [Content] Top Section - Cover Image

### ISSUE THREAD

**Issue by zshawar** [GWC-UNCC/Girls-Who-Code-at-UNCC#130]
### Languages Used
HTML

### Description of Issue
This is a cover image of girls in stem that will be under the "Logo and Intro" Section.

#### FROM:
This is not on the template.

#### TO:
![image](https://user-images.githubusercontent.com/77990816/155898502-372f9da6-85e3-4e54-984c-adb45fd02311.png)

**Comment by zshawar** [comment]
This issue is being completed with issue/about/top-section/129 -  #161

**Comment by bluelotus03** [comment]
https://github.com/GWC-UNCC/Girls-Who-Code-at-UNCC/issues/130#issuecomment-1100759950
