### ISSUE TITLE
[About] [Content] Top Section - Social Media Icons

### ISSUE THREAD

**Issue by zshawar** [GWC-UNCC/Girls-Who-Code-at-UNCC#131]
### Languages Used
HTML

### Description of Issue
Under the "cover image" section we need to include all of the social media icons for the platforms you can find us on.

#### FROM:
This is not in our template.

#### TO:
![image](https://user-images.githubusercontent.com/77990816/155898646-a0d4ed28-9d62-4287-830a-c7fe930be9fe.png)

**Comment by bluelotus03** [comment]
Completed with PR #162
