### ISSUE TITLE
[About] [Style] FAQs Section - Styling FAQ section present in About page

### ISSUE THREAD

**Issue by manaswinipolkampally** [GWC-UNCC/Girls-Who-Code-at-UNCC#133]
### Languages Used

HTML

### Description of Issue

The issue is about applying CSS properties to the FAQ section, 
1. The questions should be only visible to user unless an action performed like a click on question or click on expanded option to view the answer to the FAQ. 
2. Every question should be separated by a line.
3. All questions should be in default collapsed mode.

#### FROM:

There is no FAQ section present in an already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/22270535/155899802-f653530e-1310-48b6-ba68-0eb45d6e418d.png)
![image](https://user-images.githubusercontent.com/22270535/155899822-419b1227-2d99-466e-8011-64c30be2c582.png)

**Comment by bluelotus03** [comment]
Completed
