### ISSUE TITLE
[BUG][About] [Membership Section - Membership description styling]

### ISSUE THREAD

**Issue by LiyuGT** [GWC-UNCC/Girls-Who-Code-at-UNCC#200]
**Describe the bug**
It is a punctuation problem. I am not sure if it intentionally written as "...NinerEngage!." with the exclamation mark followed with a period.

**To Reproduce**

1. Click on About Tab
2. Scroll down to Become a Member
3. See error right under Become a Member

**Expected behavior**
Should just be "...NinerEngage!" (No period)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS (MacBook Pro)
 - Browser: Chrome
 - Version  100.0.4896.127 and release date: 2022-04-15

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro
 - OS: iOS
 - Browser: Safari
 - Version 15.4.1

**Additional context**
No :)

**Comment by bluelotus03** [comment]
Nice catch! Resolved!
