### ISSUE TITLE
[BUG][Contact]Main Section-Form

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#201]
**Describe the bug**
Form does not currently have input verification for multiple fields. Users will receive a "message sent successfully" confirmation when major fields are not filled out (email, or first/last name.) User will receive the message on any combination of missing fields (I'm not sure if all of them are strictly required though.)

**To Reproduce**
1. Go to the contact page
2. filled out form without email
3. Submit
4. See an error

**Expected behavior**
There would be some kind of input error notification on fields that are normally required in contact forms.
Also, it may be best to show which fields are optional (if any) and which are required.

**Desktop (please complete the following information):**
 **- OS:** windows
 **- Browser:** chrome
 **- Version:** 101.0.4951.41

**Smartphone (please complete the following information):**
 **- Device:** iphone11
 **- OS:** IOS 15.4.1
 **- Browser:** safari

**Additional context**
I did not try out form variations where the email field WAS filled out (and 1 other field was not) for the sake of the limit on messaging. But it is a strong assumption that users would be receiving the "success" message on any combination.

**Comment by bluelotus03** [comment]
Resolved!
