### ISSUE TITLE
[BUG][Calendar]Main Section Title Styling

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#202]
**Describe the bug**
"Check out our Events!" The exclamation point is not purple (as per the prototype.)

**To Reproduce**
1. Go to 'Calendar'

**Expected behavior**
The -span- element would cover Events! not just Events

**Screenshots**
![image](https://user-images.githubusercontent.com/92289809/165971895-b82031a8-a862-406a-aece-fe721af4f442.png)

**Desktop (please complete the following information):**
 **- OS**: Windows
 **- Browser: ** Chrome
 **- Version: **101.0.4951.41

**Comment by bluelotus03** [comment]
Resolved!
