### ISSUE TITLE
[BUG][Calendar]Browser Tab 

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#203]
**Describe the bug**
The following is in the 'page title' when the page is opened in the browser.
Check out our < span > Events </ span >!

**To Reproduce**
1. Go to 'Calendar'

**Expected behavior**
'Calendar' would be the only thing displayed in the tab's title

**Screenshots**
![image](https://user-images.githubusercontent.com/92289809/165972559-2053cf9a-a500-46b7-9750-5e70b83c21b8.png)

**Desktop (please complete the following information):**
 **- OS**: Windows
 **- Browser:** Chrome
 **- Version:** 101.0.4951.41

**Comment by DeneLogan** [comment]
The same 'bug' exists on the 'Portfolio' page (where there is HTML plain text in the tab's title.) I didn't submit a bug report since it wasn't assigned to me but I will later on, in case it is missed!

**Comment by bluelotus03** [comment]
Nice catch! Resolved!
