### ISSUE TITLE
[BUG][Portfolio] Project Pages

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#204]
**Describe the bug**
Every time you click on a project, it directs you to a page that shows a cut-off of the footer (Image shown below.) I would recommend creating a message about the unfinished page and create a button that returns the user to the previous page. 

**To Reproduce**
1. Go to "Portfolio"
2. Hover over "Web Project '22" 
3. Click on "View Project"

**Expected behavior**
When I click on a project, I expected to see a message of the uncompleted page and click on a button that sends me back to the portfolio page. 

**Screenshots**
![14](https://user-images.githubusercontent.com/97717214/166076368-3f10a432-b9ca-47e1-9512-1718a668a6a5.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by bluelotus03** [comment]
Resolved!
