### ISSUE TITLE
[BUG][Library] All Library Cards Pages #1

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#205]
**Describe the bug**
1. This is a small minor detail I noticed, but after you click on any of the cards on the library page, you can see that the date, and name are way too close to the page header (As shown on the image), and some spacing in between would be good,

**To Reproduce**
1. Go to 'Library'
2. Hover over 'Operating Systems' or any of the library cards.
3. Click on 'Read More'
4. See error on the top of the page.

**Expected behavior**
Just a bit more space. Lol

**Screenshots**
![14](https://user-images.githubusercontent.com/97717214/166077167-9814290d-3eb4-464f-858b-66a24827e00e.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 
**Additional context**
N/A

**Comment by bluelotus03** [comment]
Resolved!
