### ISSUE TITLE
[BUG][Library] All Library Card Pages #2

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#206]
**Describe the bug**
Take out the name "Alexender Schoitiz" on the top of the page right by the date. 

**To Reproduce**
1. Go to 'Library'
2. Hover over 'Operating Systems' or any of the library cards.
3. Click on 'Read More'
4. See error on the top of the page right next to the date. 

**Expected behavior**
Not seeing the name "Alexender Schoitiz".

**Screenshots**
![Uploading 14.PNG…]()

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by bluelotus03** [comment]
Resolved!
