### ISSUE TITLE
[Page] About

### ISSUE THREAD

**Issue by bluelotus03** [GWC-UNCC/Girls-Who-Code-at-UNCC#3]
### Content

- [x] #27 @zshawar 
- [x] #28 @bluelotus03 
- [x] #29 @DeneLogan 
- [x] #30 @michecamacho 
- [x] #31 @DeneLogan 
- [x] #32 @DeneLogan 
- [x] #33 @Findjules2 

### Style

- [x] #35 @DeneLogan 
- [x] #34 @Findjules2  
- [x] #36 @gadgil-devashri 
- [x] #38 @gadgil-devashri 
- [x] #39 @gadgil-devashri 
- [x] #40 @DeneLogan 
- [x] #41 @manaswinipolkampally

**Comment by michecamacho** [comment]
- [ ] #68

**Comment by bluelotus03** [comment]
Completed
