### ISSUE TITLE
[About] [Style] Teams Section - Font Color

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#62]
### Description of Issue
This issue involves the completion of the below two tasks. For each profile
1. Change the font color of the Member name field to white  (check css vars for these values)
2. Change the font color of the Team position field to Blue (check css vars for these values)

#### FROM:
![image](https://user-images.githubusercontent.com/25425769/155009241-a1faf9ff-3f97-47a8-be0c-c838990f834b.png)

#### TO:
![image](https://user-images.githubusercontent.com/25425769/155009179-f3dfd72f-42d2-439f-8963-84175e268812.png)

**Comment by bluelotus03** [comment]
Completed on main
