### ISSUE TITLE
[About] [Style] Teams Section - Background Color

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#63]
### Description of Issue
This task involves changing background-color of each team member's profile card from white to black (check css var for these values)

#### FROM:
![image](https://user-images.githubusercontent.com/25425769/155012818-166adaa0-1de0-4140-9fdb-f3afcfd48621.png)

#### TO:
![image](https://user-images.githubusercontent.com/25425769/155012713-e4ba0485-1854-481a-a846-48139dbbb2fc.png)

**Comment by bluelotus03** [comment]
Closed with PR #173
