### ISSUE TITLE
[About] [Content] FAQ Section - FAQ Text

### ISSUE THREAD

**Issue by Findjules2** [GWC-UNCC/Girls-Who-Code-at-UNCC#65]
#### FROM:

![image](https://user-images.githubusercontent.com/59750880/155037597-5f0583d6-bef1-4733-90b7-422f427bc7d0.png)
 

#### TO:
![image](https://user-images.githubusercontent.com/59750880/155037299-38125ed3-cb00-4dab-a20e-a49becb2beb6.png)

**Comment by bluelotus03** [comment]
Completed with PR #151
