### ISSUE TITLE
[About] [Style] Membership Section - Header styling 

### ISSUE THREAD

**Issue by gadgil-devashri** [GWC-UNCC/Girls-Who-Code-at-UNCC#66]
### Description of Issue
This issue covers applying the below CSS properties to the section header inside HTML element h2 - "Become a Member"
1. font-family: Montserrat;
2. font-size: 50px;
3. line-height: 61px;
4. letter-spacing: -0.02em;
5. color: #000000;

#### FROM:
There is no existing membership section in the already deployed website template

#### TO:

![image](https://user-images.githubusercontent.com/25425769/155038054-58bad2ea-fbb1-40f6-8842-6c9ab4e5cd8e.png)

**Comment by bluelotus03** [comment]
Completed
