### ISSUE TITLE
[About] [Style] Top Section - social media icons

### ISSUE THREAD

**Issue by Findjules2** [GWC-UNCC/Girls-Who-Code-at-UNCC#67]
### Description of Issue
Change social media icons to purple with their hovering effects

#### FROM:
![image](https://user-images.githubusercontent.com/59750880/155038880-5acede2e-a8db-4750-abf6-f071bbfb188a.png)

#### TO:
![image](https://user-images.githubusercontent.com/59750880/155038813-8bc4c5b2-4b1a-44ae-b8c2-1ee836205fde.png)

**Comment by bluelotus03** [comment]
Completed with PR #179
