### ISSUE TITLE
[About] [Content] Membership Section - Add Text

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#68]
### Languages Used
HTML

### Description of Issue
Add several text descriptions about membership

#### FROM:
Photo not available

#### TO:
![member](https://user-images.githubusercontent.com/97717214/155241654-b7d0130b-eb56-41ee-ad73-d9c64e52bd2d.PNG)

**Comment by bluelotus03** [comment]
Completed with PR #141
