### ISSUE TITLE
[Library] [Content] Top Section - Page Intro

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#70]
### Languages Used
HTML

### Description of Issue
Change title and intro text to the 'GWC Library' header and description below.

#### FROM:
![image](https://user-images.githubusercontent.com/92289809/155563952-dbea78c5-f0c1-490d-9d84-f396488f172a.png)

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155564004-a220b24f-724f-4527-978d-068b87c3c35c.png)

**Comment by bluelotus03** [comment]
Completed with PR #145
