### ISSUE TITLE
[About] [Style] Sponsorship Section - Font Changes

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#71]
### Languages Used
CSS, HTML

### Description of Issue
Add shadow effect to title "Sponsor Us"

#### FROM:
This does not currently exist in the template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155599818-ae941f08-c3fa-4f64-9380-6cbba36c0f4b.png)

**Comment by bluelotus03** [comment]
Completed with PR #175
