### ISSUE TITLE
[About] [Content] Sponsorship Section - Title and Intro

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#78]
### Languages Used
HTML

### Description of Issue
Add the title of section 'Sponsor Us'
Add section introduction and coming soon 
Add the jump back button (arrow) and label
Link jump back arrow and text to Get Involved section

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155606679-f348fff3-2143-4519-84c8-d74a9b1e14d4.png)

**Comment by bluelotus03** [comment]
Completed with PR #138
