### ISSUE TITLE
[About] [Content] Partnership Section - Title and Intro

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#79]
### Languages Used
HTML

### Description of Issue
Add title of section: 'Partner with Us'
Add section introduction text

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155610165-752813d4-170f-4d4d-aeab-c747665cc3db.png)

**Comment by bluelotus03** [comment]
Completed with PR #139
