### ISSUE TITLE
[About] [Content] Partnership Section - We Host

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#80]
### Languages Used
HTML

### Description of Issue
Add header text
Add numbered list with appropriate text

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155610508-d2a7e2be-6786-409e-9c92-11c8d8e77ded.png)

**Comment by bluelotus03** [comment]
Completed with PR #139
