### ISSUE TITLE
[About] [Content]  Partnership Section - You Host

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#81]
### Languages Used
HTML

### Description of Issue
Add header text
Add numbered list and appropriate text

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155610735-0ba0ddcd-9765-4918-905c-67451793fba7.png)

**Comment by bluelotus03** [comment]
Completed with PR #139
