### ISSUE TITLE
[About] [Content] Partnership Section - Event Options

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#82]
### Languages Used
HTML

### Description of Issue
Add header text
Add option titles in bold and in-line with 'Bullet-Pt-Stars'
Add option descriptions.

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155611222-536f3bd1-4197-48c6-b027-92d4670a0f47.png)

**Comment by bluelotus03** [comment]
Completed with PR #139
