### ISSUE TITLE
[About] [Content] Partnership Section - Prev Events

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#83]
### Languages Used
HTML

### Description of Issue
Add header text
Add previous events introduction

#### FROM:
This section does not exist in current template.

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155611442-9a72f1ff-a97c-491d-b817-a990c9869cc4.png)

**Comment by bluelotus03** [comment]
Completed with PR #168
