### ISSUE TITLE
[About] [Content] Get Connected Section - Header 

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#84]
### Languages Used
HTML

### Description of Issue
Change header text
Add (?) icon
Add 'FAQ' text 

#### FROM:
![image](https://user-images.githubusercontent.com/92289809/155610762-3c4be055-3370-41f3-8c24-e84940053702.png)

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155612051-748bf74a-9824-45b2-9d5e-711d286e925d.png)

**Comment by bluelotus03** [comment]
Will cover this in styling, less complicated than separate pieces for this section.
