### ISSUE TITLE
[About] [Content] Get Connected Section - Option Cards

### ISSUE THREAD

**Issue by DeneLogan** [GWC-UNCC/Girls-Who-Code-at-UNCC#85]
### Languages Used
HTML

### Description of Issue
Add mini-section headers for each: 'Membership', 'Partnership', and 'Sponsorship'
Add corresponding description text for each mini-section
Add 'Learn More' links to each section.

#### FROM:
![image](https://user-images.githubusercontent.com/92289809/155610762-3c4be055-3370-41f3-8c24-e84940053702.png)

#### TO:
![image](https://user-images.githubusercontent.com/92289809/155612752-91d35bf7-0bb4-4dee-ad11-b78762d57e7d.png)

**Comment by bluelotus03** [comment]
Will cover this in styling, less complicated than separate pieces for this section.
