### ISSUE TITLE
[Home] [Content] Top Section- Stats Bar

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#86]
### Description of Issue
1, Add stats bar: "170+ Members, 10+ technical projects, 5+ partners, 25+ total events".

#### FROM:
![screenshot](https://user-images.githubusercontent.com/97717214/155904009-b4f290ae-84b9-4fcc-857a-52bf910ed52b.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155904006-4f29b875-cc8b-460b-ad61-819cab0d58bc.PNG)

**Comment by bluelotus03** [comment]
Completed with PR #142
