### ISSUE TITLE
[Home] [Content] Quotes Section - Add text 

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#87]
### Description of Issue
1. Title: What People Say
2. Add a quote
3. Add Name
4. Underneath the name, add the word, "Member,"
5. Add the graduating semester and year

#### FROM:

![screenshot](https://user-images.githubusercontent.com/97717214/155635130-286cbd13-fbe2-4bb0-807f-caded981568b.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155635096-28d80108-4718-4f72-a8ba-0712b0e80938.PNG)

**Comment by bluelotus03** [comment]
Completed with PR #153
