### ISSUE TITLE
[Home] [Style] Navbar Section - Add Nav Bar

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#89]
### Description of Issue
Need to implement the navigation bar at the top of the page.

#### FROM:

![screenshot](https://user-images.githubusercontent.com/97717214/155651777-c5df45e2-a840-4ff8-a129-6dd35adca289.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155651766-c1337ce7-b895-46cc-9a96-90a523b6b704.PNG)

**Comment by bluelotus03** [comment]
Completed
