### ISSUE TITLE
[Home] [Style] Main Section - Black Background

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#90]
### Description of Issue

1. Change the background color to black

#### FROM:
![screenshot](https://user-images.githubusercontent.com/97717214/155904361-eaf0e463-0f0f-4a72-9947-075441453186.PNG)

#### TO:
![shot](https://user-images.githubusercontent.com/97717214/155904350-c8b4acfc-5d72-465a-a260-de0c4776a9b7.PNG)

**Comment by bluelotus03** [comment]
Completed with PR #143
