### ISSUE TITLE
[Home] [Style] Main Section - Logo Positioning 

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#92]
### Description of Issue
1. Insert logo
2. Change logo size
3. Set the position of the logo, "Left-Centered"

#### FROM:

![screenshot](https://user-images.githubusercontent.com/97717214/155904506-70d30e96-47b1-4bc4-b453-7838b3668568.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155904500-e747a057-4c21-4f0d-9e7d-a94fbb2e8866.PNG)

**Comment by bluelotus03** [comment]
Closed with PR #143
