### ISSUE TITLE
[Home] [Style] Quotes Section - Font Format

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#93]
### Description of Issue

1. Make the font color white
2.  Position it to the center
3. Increase the font size

#### FROM:

![screenshot](https://user-images.githubusercontent.com/97717214/155705527-5805be71-636e-4274-80ff-a76f9fcbb18d.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155705554-538e6a7f-bdf8-4b4d-b119-2b93ce48fd58.PNG)

**Comment by bluelotus03** [comment]
Completed with PR #181
