### ISSUE TITLE
[Home] [Style] Quotes Section - Add Purple Block

### ISSUE THREAD

**Issue by michecamacho** [GWC-UNCC/Girls-Who-Code-at-UNCC#94]
### Description of Issue

1. Add a purple block as a background for the quote section.

#### FROM:

![screenshot](https://user-images.githubusercontent.com/97717214/155706335-bea32d04-806c-48ee-a25a-de1e326bed78.PNG)

#### TO:

![shot](https://user-images.githubusercontent.com/97717214/155706316-cb2c7f6f-89bd-4ad7-8165-6fb912a337aa.PNG)

**Comment by bluelotus03** [comment]
Completed with PR https://github.com/GWC-UNCC/Girls-Who-Code-at-UNCC/pull/181
